spring:
  application:
    name: syncfit-wishlist-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${WISHLIST_SPRING_DATASOURCE_URL}
    username: ${WISHLIST_SPRING_DATASOURCE_USERNAME}
    password: ${WISHLIST_SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update