server:
  port: 20000
spring:
  application:
    name: syncfit-wishlist-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${WISHLIST_SPRING_DATASOURCE_URL}
    username: ${WISHLIST_SPRING_DATASOURCE_USERNAME}
    password: ${WISHLIST_SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka